FROM opensuse/leap:15.5
RUN zypper -n in python311 python311-pip python311-devel python311-setuptools python311-tools tar patch gcc gzip libusb-devel git
# Normally this is not reccomended, but needed for GHA
RUN pip3.11 install build
ADD ./github-run.sh /opt
ENTRYPOINT [ "sh", "-c" ]
CMD [ "/opt/github-run.sh" ]
