name: 'Klippy Build'
description: 'Builds klippy for x86_64 with OpenSuse Leap'
inputs: {}
oututs: {}
runs:
  using: 'docker'
  image: 'docker://ghcr.io/laikulo/klippy-tooling/repackager:laikulo-klipper'
  args: []
