on:
  push:
    branches:
     - nonexistant
  workflow_dispatch: {}

jobs:
  build:
    name: build x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Build
        uses: ./.gitlab/actions/build-klipper

