on:
  schedule:
  - cron: "0 */3 * * ?"
  workflow_dispatch:

jobs:
  sync_master:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVKEY }}
          
      - name: Sync klipper fork master branch
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token }}
        run: gh repo sync Laikulo/Klipper -b master
